import { useEffect, useState, type CSSProperties, type FormEvent } from 'react'
import type { CartResponse, OrderResponse, ProductDetails, ProductSummary } from '@mobilemarket/shared'
import { api } from './services/api'
import './App.css'

type View = 'shop' | 'detail' | 'cart' | 'checkout' | 'confirmation'
type CheckoutForm = { customerName: string; phoneNumber: string; shippingAddress: string; city: string; email: string; postalCode: string }

const fallbackImages = [
  'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=900&q=85',
  'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=900&q=85',
  'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=900&q=85',
  'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=85',
  'https://images.unsplash.com/photo-1556656793-08538906a9f8?auto=format&fit=crop&w=900&q=85',
]
const money = (value: number) => `$${value.toLocaleString('en-US')}`
const imageFor = (product: ProductSummary) => product.imageUrl || fallbackImages[(product.id - 1) % fallbackImages.length]
const emailPattern = /^[^@\s]+@[^@\s]+\.[^@\s]+$/
const phonePattern = /^\+?[0-9 ()-]{7,24}$/
const postalPattern = /^[a-zA-Z0-9][a-zA-Z0-9 -]{2,19}$/

function App() {
  const [view, setView] = useState<View>('shop')
  const [products, setProducts] = useState<ProductSummary[]>([])
  const [selected, setSelected] = useState<ProductDetails | null>(null)
   const [detailNotFound, setDetailNotFound] = useState(false)
  const [detailQuantity, setDetailQuantity] = useState(1)
  const [cart, setCart] = useState<CartResponse | null>(null)
  const [order, setOrder] = useState<OrderResponse | null>(null)
  const [query, setQuery] = useState('')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({})
  const [form, setForm] = useState<CheckoutForm>({ customerName: '', phoneNumber: '', shippingAddress: '', city: '', email: '', postalCode: '' })

  const loadCart = async () => setCart(await api.cart())
  useEffect(() => { Promise.all([api.products(''), api.cart()]).then(([items, nextCart]) => { setProducts(items); setCart(nextCart) }).catch((cause: Error) => setError(cause.message)).finally(() => setLoading(false)) }, [])
   useEffect(() => { const pathId = window.location.pathname.match(/^\/products\/(\d+)$/)?.[1]; if (!pathId) return; setView('detail'); api.product(Number(pathId)).then((product) => { setSelected(product); setDetailNotFound(false) }).catch(() => setDetailNotFound(true)); }, [])
  useEffect(() => { const timer = setTimeout(() => { api.products(query).then(setProducts).catch((cause: Error) => setError(cause.message)) }, 250); return () => clearTimeout(timer) }, [query])

  const run = async (action: () => Promise<void>) => { setError(''); try { await action() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Request failed') } }
  const addToCart = (product: ProductSummary, quantity = 1) => run(async () => { await api.addToCart(product.id, quantity); await loadCart(); setView('cart') })
  const updateQuantity = (id: number, quantity: number) => run(async () => { await api.updateCartItem(id, quantity); await loadCart() })
  const removeItem = (id: number) => run(async () => { await api.removeCartItem(id); await loadCart() })
  const openDetail = (product: ProductSummary) => run(async () => { window.history.pushState({}, '', `/products/${product.id}`); setSelected(await api.product(product.id)); setDetailNotFound(false); setDetailQuantity(1); setView('detail') })
  const openCheckout = () => run(async () => { const freshCart = await api.cart(); setCart(freshCart); const staleItem = freshCart.items.find((item) => item.quantity > item.product.stockQuantity); if (staleItem) { setError(`${staleItem.product.name} has only ${staleItem.product.stockQuantity} in stock. Adjust the quantity before checkout.`); return } setView('checkout') })
  const placeOrder = (event: FormEvent) => { event.preventDefault(); const errors: Record<string, string> = {}; for (const key of ['customerName', 'shippingAddress', 'city'] as const) { const value = form[key].trim(); if (!value) errors[key] = 'This field is required.'; else if (value.length > 200) errors[key] = 'Maximum length is 200 characters.' } const phone = form.phoneNumber.trim(); if (!phone) errors.phoneNumber = 'This field is required.'; else if (!phonePattern.test(phone) || phone.replace(/\D/g, '').length < 7 || phone.replace(/\D/g, '').length > 20) errors.phoneNumber = 'Enter a valid phone number.'; const email = form.email.trim(); if (email && (email.length > 254 || !emailPattern.test(email))) errors.email = 'Enter a valid email address.'; const postalCode = form.postalCode.trim(); if (postalCode && !postalPattern.test(postalCode)) errors.postalCode = 'Enter a valid postal code.'; setFieldErrors(errors); if (Object.keys(errors).length) return; run(async () => { const created = await api.createOrder(form); setOrder(await api.order(created.orderNumber)); setCart({ ...(cart as CartResponse), items: [], totalAmount: 0 }); setView('confirmation') }) }
  const items = cart?.items || []
  const total = cart?.totalAmount || 0

  return <div className="app-shell">
    <header className="topbar"><button className="brand" onClick={() => setView('shop')}><span className="brand-mark">M</span> mobile<span>market</span></button><nav><button className={view === 'shop' ? 'active' : ''} onClick={() => setView('shop')}>Shop</button><button onClick={() => setView('cart')} className="cart-link">Cart <b>{items.reduce((sum, item) => sum + item.quantity, 0)}</b></button></nav></header>
    {error && <div role="alert" className="api-error">{error}</div>}
    {loading ? <main><p className="lede">Loading the current lineup...</p></main> : view === 'shop' && <main><section className="intro"><p className="eyebrow">CURATED DEVICES / 2026</p><h1>Find your<br /><em>next phone.</em></h1><p className="lede">A focused collection of high-demand phones, ready for wherever the day takes you.</p><div className="search"><span>⌕</span><input aria-label="Search products" placeholder="Search by name or brand" value={query} onChange={(event) => setQuery(event.target.value)} /></div></section><section className="catalog"><div className="section-heading"><h2>{query ? `Results for “${query}”` : 'The current lineup'}</h2><span>{products.length} devices</span></div>{products.length === 0 ? <div className="empty"><p>No phones match that search.</p></div> : <div className="product-grid">{products.map((product, index) => <article className="product-card" key={product.id} style={{ '--delay': `${index * 70}ms` } as CSSProperties}><button className="product-image" onClick={() => openDetail(product)}><img src={imageFor(product)} alt={product.name} /><span>{product.stockQuantity > 0 ? `${product.stockQuantity} in stock` : 'Out of stock'}</span></button><div className="product-meta"><p className="brand-label">{product.brand}</p><h3>{product.name}</h3><p className="product-description">{product.description}</p><div className="product-buy"><strong>{money(product.price)}</strong><button className="add-button" aria-label={`Add ${product.name} to cart`} onClick={() => addToCart(product)} disabled={product.stockQuantity === 0}>+</button></div></div></article>)}</div>}</section></main>}
    {view === 'detail' && (selected ? <main className="detail"><button className="back" onClick={() => { window.history.pushState({}, '', '/'); setView('shop') }}>← Back to shop</button><div className="detail-layout"><div className="detail-image"><img src={imageFor(selected)} alt={selected.name} /></div><div className="detail-copy"><p className="eyebrow">{selected.brand}</p><h1>{selected.name}</h1><p className="detail-price">{money(selected.price)}</p><p className="lede">{selected.description}</p><p className="stock-note">{selected.stockQuantity > 0 ? `${selected.stockQuantity} in stock` : 'Out of stock'}</p><ul>{selected.specifications.split('|').map((spec) => <li key={spec}>{spec}</li>)}</ul><div className="quantity"><button aria-label="Decrease quantity" onClick={() => setDetailQuantity(Math.max(1, detailQuantity - 1))} disabled={detailQuantity === 1}>−</button><span aria-label="Quantity">{detailQuantity}</span><button aria-label="Increase quantity" onClick={() => setDetailQuantity(Math.min(selected.stockQuantity, detailQuantity + 1))} disabled={detailQuantity >= selected.stockQuantity}>+</button></div><button className="primary-button" onClick={() => addToCart(selected, detailQuantity)} disabled={selected.stockQuantity === 0}>Add to cart <span>→</span></button></div></div></main> : detailNotFound && <main className="detail"><button className="back" onClick={() => { window.history.pushState({}, '', '/'); setView('shop') }}>← Back to shop</button><div className="empty"><h1>Product not found</h1><p>This phone is no longer available.</p></div></main>)}
    {view === 'cart' && <main className="cart-page"><div className="page-heading"><p className="eyebrow">YOUR SELECTION</p><h1>Shopping cart</h1></div>{items.length === 0 ? <div className="empty"><p>Your cart is waiting for something good.</p><button className="primary-button" onClick={() => setView('shop')}>Browse phones →</button></div> : <div className="cart-layout"><div className="cart-items">{items.map((item) => <div className="cart-item" key={item.id}><img src={imageFor(item.product)} alt="" /><div><p className="brand-label">{item.product.brand}</p><h3>{item.product.name}</h3><button className="remove" onClick={() => removeItem(item.id)}>Remove</button></div><div className="quantity"><button onClick={() => updateQuantity(item.id, item.quantity - 1)} disabled={item.quantity === 1}>−</button><span>{item.quantity}</span><button onClick={() => updateQuantity(item.id, item.quantity + 1)} disabled={item.quantity >= item.product.stockQuantity}>+</button></div><strong>{money(item.subtotal)}</strong></div>)}<button className="continue" onClick={() => setView('shop')}>← Continue shopping</button></div><aside className="summary"><p className="eyebrow">ORDER SUMMARY</p><div><span>Subtotal</span><strong>{money(total)}</strong></div><div><span>Delivery</span><strong>Free</strong></div><hr /><div className="grand"><span>Total</span><strong>{money(total)}</strong></div><button className="primary-button" onClick={openCheckout}>Checkout <span>→</span></button></aside></div>}</main>}
    {view === 'checkout' && <main className="checkout"><button className="back" onClick={() => setView('cart')}>← Back to cart</button><div className="page-heading"><p className="eyebrow">ALMOST THERE</p><h1>Checkout</h1></div><form onSubmit={placeOrder}><div className="form-section"><h2>Delivery details</h2><div className="form-grid">{([['customerName', 'Full name', true], ['phoneNumber', 'Phone number', true], ['shippingAddress', 'Shipping address', true], ['city', 'City', true], ['postalCode', 'Postal code', false], ['email', 'Email', false]] as const).map(([key, label, required]) => <label key={key} htmlFor={key} className={key === 'shippingAddress' || key === 'email' ? 'wide' : ''}>{label}{required && <span className="required-mark" aria-hidden="true">*</span>}{!required && <small>optional</small>}<input id={key} aria-invalid={Boolean(fieldErrors[key])} aria-describedby={fieldErrors[key] ? `${key}-error` : undefined} required={required} type={key === 'email' ? 'email' : key === 'phoneNumber' ? 'tel' : 'text'} value={form[key]} onChange={(event) => { setForm({ ...form, [key]: event.target.value }); setFieldErrors({ ...fieldErrors, [key]: '' }) }} />{fieldErrors[key] && <small id={`${key}-error`} role="alert">{fieldErrors[key]}</small>}</label>)}</div></div><div className="form-section"><h2>Review order</h2>{items.map((item) => <div className="confirm-item" key={item.id}><span>{item.product.name} ×{item.quantity} <small>{money(item.unitPrice)} each</small></span><strong>{money(item.subtotal)}</strong></div>)}<div className="confirm-total"><span>Total</span><strong>{money(total)}</strong></div></div><div className="form-section payment"><h2>Payment method</h2><label className="payment-option"><input type="radio" checked readOnly /><span><b>Cash on Delivery</b><small>Pay when your package arrives</small></span><span className="check">✓</span></label></div><div className="checkout-footer"><div><span>Total to pay</span><strong>{money(total)}</strong></div><button className="primary-button" type="submit">Place order <span>→</span></button></div></form></main>}
    {view === 'confirmation' && order && <main className="confirmation"><div className="success-mark">✓</div><p className="eyebrow">ORDER RECEIVED</p><h1>Thank you, {order.customerName.split(' ')[0]}.</h1><p className="lede">Your order is on its way to becoming real. We’ll prepare it with care.</p><div className="order-number">Order number <strong>{order.orderNumber}</strong></div><div className="confirmation-grid"><section><p className="eyebrow">ITEMS</p>{order.items.map((item) => <div className="confirm-item" key={item.id}><span>{item.productName} <b>×{item.quantity}</b></span><strong>{money(item.subtotal)}</strong></div>)}<div className="confirm-total"><span>Total</span><strong>{money(order.totalAmount)}</strong></div></section><section><p className="eyebrow">DELIVERY</p><p>{order.shippingAddress}<br />{order.city}{order.postalCode && `, ${order.postalCode}`}</p><p className="eyebrow space-top">PAYMENT</p><p>Cash on Delivery<br /><span className="status">● {order.status}</span></p></section></div><button className="primary-button" onClick={() => setView('shop')}>Continue shopping <span>→</span></button></main>}
    <footer>mobilemarket <span>New devices, clear decisions.</span></footer>
  </div>
}

export default App
